version: '3.9'

services:
  store-app:
    image: todo-app
    container_name: todo-app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5050:5050'
